Threefold links
deltaDAO/mvg-hackathon-overview pull request #23
Opened 2022-03-08 13:00 UTC by gmachtel

Fixes #

## Proposed Changes

  - Add ThreeFold repos
  -
  -

2022-03-08 13:16 UTC, moritzkirstein requested changes
Thanks for the submission of those resources!
To successfully deploy the changes, please resolve JSON parsing errors.

@kaimeinke please have a look at where these resources fit best, and verify if a new category / track is the correct solution here.

2022-03-08 13:16 UTC, moritzkirstein commented on content/resources.json
> +        },
The resource array from the previous category as well as the category then need to be closed here.
replace the `},` with
```
    }
  ]
},
```

2022-03-08 13:16 UTC, moritzkirstein commented on content/resources.json
>        ]
remove `]`

2022-03-08 13:38 UTC, gmachtel reviewed
Now added as separate track, but idea was to have it as subtract of 6-MVG

2022-03-18 10:56 UTC, kaimeinke commented
Dear @gmachtel , i fixed the errors and put the content changes to https://github.com/deltaDAO/mvg-hackathon-overview/pull/24.
Best Kai

2022-03-18 10:56 UTC, closed without merging