Renamed Pilot-004 and Confidential Computing
deltaDAO/mvg-hackathon-overview pull request #5
Opened 2021-11-26 17:42 UTC by mpilka

Renamed items so naming is more consistent:
* "Pilot 004" -> "Data-to-Compute ", because we also have "Compute-to-Data"
* "Confidential Computing" -> "CC", because we also have "EDC" and "SCS"

2021-11-27 08:50 UTC, oceanByte requested changes

2021-11-27 08:50 UTC, oceanByte commented on content/resources.json
> +      "title": "CC",
issue, suggestion(blocking): I think CC is confusing to newcomers. I suggest sticking with Confidential Computing as this is precise and clear for everyone. Let me know if this works for you or if I am missing something.

2021-11-27 08:50 UTC, oceanByte commented on content/resources.json
> +      "title": "Data-to-Compute",
agreed. Was already merged with the previous PR https://github.com/deltaDAO/mvg-hackathon-overview/pull/4

2021-11-30 07:00 UTC, mpilka commented
Already merged, closing this

2021-11-30 07:00 UTC, closed without merging